-- PostgreSQL schema for the "enrollee" table
-- Column order matches "AVERT Data Dictionary_2026_09_07_en.xlsx" (enrollee_dd
-- sheet), in the order FieldName rows appear there.
--
-- Column types are pulled from that sheet's FieldType column:
--   integer      -> INTEGER
--   text_decimal -> NUMERIC
--   date         -> DATE
--   datetime     -> TIMESTAMP
--   text         -> TEXT
--
-- Exceptions to the dictionary's literal FieldType:
--   phonenumber_ug, phonenumber_bf: dictionary says integer, but Burkina Faso
--   numbers in the data start with a leading 0 (e.g. "06346704"). INTEGER
--   would silently drop that digit and corrupt the number, so these are TEXT.
--
--   mrc, subcounty, parish, village: dictionary says integer, but these hold
--   zero-padded location codes (e.g. "008", "01") matching the villages
--   reference sheet. Kept as TEXT to preserve the padding.
--
-- Fields the dictionary doesn't document at all -- device/app metadata
-- (uniqueid, swver, device, lastmod, survey_id, synced_at) and a few
-- undocumented survey fields still sent by the app (age_at_sep2023,
-- age_eligible_ug, age_eligible_bf, age_warning, age_warning_reason,
-- symptoms_oth) -- are appended after the dictionary-ordered fields, in
-- their previous relative order, since the dictionary gives no position for
-- them. NOTE: age_warning/age_warning_reason may be stale names -- the
-- current dictionary only has age_warning_ug/age_warning_bf (split by
-- country, matching age_eligible_ug/bf and age_in_range_ug/bf) with no
-- unsplit "age_warning" entry. Left as-is here since renaming an
-- already-populated column is a separate decision from adding the new
-- fields below; worth confirming with whoever maintains the dictionary.
--
-- New in this version (2026-09-07 dictionary): admitted_yn, admitted_when,
-- and eight time_start_*/time_eligible/time_ineligible timestamp fields
-- marking when each form section began.
--
-- id is a Postgres-native surrogate key (the source data has no primary
-- key); import_pipeline.py already excludes it from the CSV load.

DROP TABLE IF EXISTS enrollee;

CREATE TABLE enrollee (
    id                          SERIAL PRIMARY KEY,
    starttime                   TIMESTAMP,
    startdate                   DATE,
    deviceid                    INTEGER,
    deviceid2                   INTEGER,
    country                     INTEGER,
    mrc                         TEXT,
    mrc2                        TEXT,
    subjid                      TEXT,
    district                    INTEGER,
    subcounty                   TEXT,
    parish                      TEXT,
    village                     TEXT,
    placeofresidence            TEXT,
    dob                         DATE,
    age_calculated              INTEGER,
    agemonths_calculated        INTEGER,
    age_at_apr2025              INTEGER,
    age_in_range_ug             INTEGER,
    age_in_range_bf             INTEGER,
    age                         INTEGER,
    agemonths                   INTEGER,
    age_eligible                INTEGER,
    catchment_eligible          INTEGER,
    mal_test_eligible           INTEGER,
    ill_noteligible             INTEGER,
    consent_eligible            INTEGER,
    reason_refused              INTEGER,
    reason_refused_oth          TEXT,
    first_enroll                INTEGER,
    last_enroll_14plus          INTEGER,
    pos_last_vis                INTEGER,
    neg_within7days             INTEGER,
    prev_enroll_pilot           INTEGER,
    prev_barcode_pilot          TEXT,
    prev_barcode                TEXT,
    time_ineligible             TIMESTAMP,
    time_eligible               TIMESTAMP,
    participantsname            TEXT,
    gender                      INTEGER,
    consent                     INTEGER,
    consent2                    INTEGER,
    barcode                     TEXT,
    barcode2                    TEXT,
    enroll_immrse               INTEGER,
    fpbarcode1_immrse           TEXT,
    fpbarcode2_immrse           TEXT,
    time_start_malaria_diag     TIMESTAMP,
    admitted_yn                 INTEGER,
    admitted_when               DATE,
    diagnostic                  INTEGER,
    result                      INTEGER,
    symptoms                    TEXT,
    time_start_vac_coverage     TIMESTAMP,
    vx_card                     INTEGER,
    vx_card_only                INTEGER,
    vx_card_no                  INTEGER,
    vx_card_no_oth              TEXT,
    vx_card_ver_plan            INTEGER,
    hasphonenumber              INTEGER,
    phonenumber_ug              TEXT,
    phonenumber_bf              TEXT,
    need_vac_cov                INTEGER,
    vx_doses_received_rtss      INTEGER,
    vx_any                      INTEGER,
    vx_any_no                   INTEGER,
    vx_any_no_oth               TEXT,
    vx_doses_received           INTEGER,
    vx_doses_received_ver       INTEGER,
    vx_doses_received_ver_oth   TEXT,
    vx_dose1_where              INTEGER,
    vx_dose1_where_oth          TEXT,
    vx_dose1_date               DATE,
    vx_dose1_date_ver           INTEGER,
    vx_dose1_date_ver_oth       TEXT,
    vx_dose2_where              INTEGER,
    vx_dose2_where_oth          TEXT,
    vx_dose2_date               DATE,
    dose2_warning_time          INTEGER,
    vx_dose2_datecheck          INTEGER,
    vx_dose2_date_ver           INTEGER,
    vx_dose2_date_ver_oth       TEXT,
    vx_dose3_where              INTEGER,
    vx_dose3_where_oth          TEXT,
    vx_dose3_date               DATE,
    dose3_warning_time          INTEGER,
    vx_dose3_datecheck          INTEGER,
    vx_dose3_date_ver           INTEGER,
    vx_dose3_date_ver_oth       TEXT,
    vx_dose4_where              INTEGER,
    vx_dose4_where_oth          TEXT,
    vx_dose4_date               DATE,
    dose4_warning_time          INTEGER,
    vx_dose4_datecheck_ug       INTEGER,
    vx_dose4_datecheck_bf       INTEGER,
    vx_dose4_date_ver           INTEGER,
    vx_dose4_date_ver_oth       TEXT,
    vx_dose_ver_any             INTEGER,
    vx_dose_ver_mismatch        INTEGER,
    vx_dose_summary             INTEGER,
    days_since_dose1            INTEGER,
    days_since_dose2            INTEGER,
    days_dose1_to_dose2         INTEGER,
    days_dose2_to_dose3         INTEGER,
    vx_doses_miss               INTEGER,
    vx_doses_miss_reas          INTEGER,
    vx_doses_miss_reas_oth      TEXT,
    vx_dose_off_sched           INTEGER,
    vx_doses_offsched_reas      INTEGER,
    vx_offsched_miss_reas_oth   TEXT,
    time_start_mal_risk_factors TIMESTAMP,
    wall_material               INTEGER,
    roof_material               INTEGER,
    structuresprayed            INTEGER,
    tspray                      INTEGER,
    spray_wash                  INTEGER,
    timetobed                   INTEGER,
    bednetlastnight             INTEGER,
    bednettwoweeks              INTEGER,
    bednet_age                  INTEGER,
    bednet_type                 INTEGER,
    bednet_type_oth             TEXT,
    child_num_sleep             INTEGER,
    prevdiag                    INTEGER,
    prevdiag_when               INTEGER,
    prevdiag_lastmonth          INTEGER,
    prevdiag_al                 INTEGER,
    prevdiag_othermeds          INTEGER,
    prevdiag_descothermed       TEXT,
    time_start_smc              TIMESTAMP,
    smc_knw                     INTEGER,
    smc_dis_com                 INTEGER,
    smc_dis_hh                  INTEGER,
    smc_month                   INTEGER,
    smc_dose1                   INTEGER,
    smc_add_days                INTEGER,
    smc_dose2                   INTEGER,
    smc_dose3                   INTEGER,
    missed_dose                 INTEGER,
    smc_reason_nodose           TEXT,
    smc_reason_nodose_oth       TEXT,
    time_start_nutrition        TIMESTAMP,
    malnourish                  INTEGER,
    malnourish_when             INTEGER,
    malnourish_trt              INTEGER,
    height                      NUMERIC,
    weight                      NUMERIC,
    muac                        NUMERIC,
    time_start_household        TIMESTAMP,
    caregiver_name              TEXT,
    caregiver_age               INTEGER,
    momeduclevel                INTEGER,
    npeople                     INTEGER,
    livestock                   INTEGER,
    cattle                      INTEGER,
    sheep                       INTEGER,
    horses                      INTEGER,
    donkeys                     INTEGER,
    pigs                        INTEGER,
    poultry                     INTEGER,
    swater                      INTEGER,
    tfaclty                     INTEGER,
    fueltype                    INTEGER,
    senergy                     INTEGER,
    sleepingstructures          INTEGER,
    electricity                 INTEGER,
    radio                       INTEGER,
    cassette                    INTEGER,
    tv                          INTEGER,
    fridge                      INTEGER,
    tble                        INTEGER,
    chair                       INTEGER,
    sofa                        INTEGER,
    bed                         INTEGER,
    cupboard                    INTEGER,
    clock                       INTEGER,
    mobile                      INTEGER,
    watch                       INTEGER,
    bicycle                     INTEGER,
    scooter                     INTEGER,
    car                         INTEGER,
    mboat                       INTEGER,
    nomboat                     INTEGER,
    bankacco                    INTEGER,
    internet                    INTEGER,
    smartphone                  INTEGER,
    tablet                      INTEGER,
    laptop                      INTEGER,
    desktop                     INTEGER,
    numaland_ug                 NUMERIC,
    numaland_bf                 NUMERIC,
    dmarkt                      NUMERIC,
    hhmeals                     INTEGER,
    hhnumt                      INTEGER,
    hhpsf                       INTEGER,
    hhh_occupation              INTEGER,
    hh_occupation_oth           TEXT,
    hhheadeduclevel             INTEGER,
    money_recieve               INTEGER,
    money_recieve_who           TEXT,
    money_recieve_who_oth       TEXT,
    ses                         INTEGER,
    comments                    TEXT,
    stoptime                    TIMESTAMP,
    age_at_sep2023              INTEGER,
    age_eligible_ug             INTEGER,
    age_eligible_bf             INTEGER,
    age_warning                 INTEGER,
    age_warning_reason          TEXT,
    symptoms_oth                TEXT,
    device                      TEXT,
    uniqueid                    TEXT,
    swver                       TEXT,
    survey_id                   TEXT,
    lastmod                     TIMESTAMP,
    synced_at                   TEXT
);
